version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: 'md5'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  broker:
    image: redis:7
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]


  api:
    build:
      context: .
    tty: false
    volumes:
      - .:/code
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy



volumes:
  api:
  db:
    driver: local