# Generated by Django 4.1.7 on 2023-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
