# Generated by Django 4.1.7 on 2023-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hash_key',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
