# Generated by Django 4.1.7 on 2023-03-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_hash_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
