# Generated by Django 4.1.7 on 2023-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course_name')),
                ('description', models.TextField(max_length=1000)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('link', models.CharField(max_length=254, verbose_name='video_link')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
    ]
